name: Updates API calls

on:
  schedule:
    - cron: '7 3 1 * *'

jobs:
  update_api_calls:
    name: Updates API calls
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Checkout aws-sdk
        uses: actions/checkout@v3
        with:
          repository: aws/aws-sdk-js
          path: enumerate_iam/aws-sdk-js

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Run generate brute force
        run: |
          cd enumerate_iam/
          python3 generate_bruteforce_tests.py
          rm -rf aws-sdk-js
          git status

      - name: Publish
        run: |
          git config --local user.email "github-actions@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -am "update: Updated API calls"
          git push origin
